# Spring Boot application configuration properties
ds:
  openai:
    api-key: # OpenAI API key
    model: gpt-4o # OpenAI model
    output-tokens: 4096 # OpenAI max output tokens
    api-endpoint: https://api.openai.com/v1/chat/completions
    system-prompt: "You are a helpful assistant."
